name: fluttered
description: A Flutter package that comes with various widgets and other helpers to reduce boiler plate code.
version: 2.0.2
homepage: https://github.com/arabbani/fluttered

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0+1
  shared_preferences: ^0.5.3+4
  connectivity: ^0.4.3+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
